const IDS = {
    COUNTRIES: 'countries',
    MULTI: 'multi',
    PERIOD_MULTI: 'periodMulti',
    PERIOD_START_DATE: 'periodStartDate',
    PERIOD_END_DATE: 'periodEndDate',
    NUMBER_OF_DAYS: 'numberOfDays',
    CURRENCY: 'currency',
    INSURANCE_SUM: 'insuranceSum',
    SPORTS: 'sports',
    SECOND_PROGRAMS: 'secondPrograms',
    PROMOCODE: 'promocode',
    PROMOCODE_OR_BONUSES: 'promocodeOrBonuses',
    BONUSES: 'bonuses',
    INSUREDS: 'insureds',
    BIRTHDAY: 'birthday',
    FIRST_NAME: 'firstName',
    LAST_NAME: 'lastName',
    MIDDLE_NAME: 'middleName',
    ADDRESS: 'address',
    INSURANT: 'insurant',
    INSURANT_EMAIL: ['insurant', 'email'],
    INSURANT_PHONE: ['insurant', 'phone'],
    INSURANT_ADDRESS: ['insurant', 'address'],
    INSURANT_PASSPORT_SERIAL: ['insurant', 'passportSerial'],
    INSURANT_PASSPORT_NUMBER: ['insurant', 'passportNumber'],
    INSURANT_PASSPORT_DATE_OF_ISSUE: ['insurant', 'passportDateOfIssue'],
    INSURANT_FIRST_NAME: ['insurant', 'firstName'],
    INSURANT_LAST_NAME: ['insurant', 'lastName'],
    INSURANT_MIDDLE_NAME: ['insurant', 'middleName'],
    INSURANT_BIRTHDAY: ['insurant', 'birthday'],
    PASSPORT_SERIAL: 'passportSerial',
    PASSPORT_NUMBER: 'passportNumber',
    OPTIONS: 'options',
    ASSISTANCE: 'assistance',
    COVID: 'covid',
    AGREEMENT_WITH_RULES: 'agreementWithRules',
    AGREEMENT_WITH_PROTECTION_POLICY: 'agreementWithProtectionPolicy',
    INSURED_IS_INSURANT_ID: 'insuredIsInsurantId',
}

export default IDS
